document.writeln("<div class=\'article_main_right_top\'>");
document.writeln("					<!-- Swiper -->");
document.writeln("					  <div class=\'swiper-container\'>");
document.writeln("						<div class=\'swiper-wrapper\'>");
document.writeln("						  <div class=\'swiper-slide\'>");
document.writeln("						  	<a href=\'http://www.hqyj.com/zhuanti/2019shujia.html\' target=\'_blank\'><img src=\'http://www.hqyj.com/Ver201811/jiuye/images/article_main_03.jpg\' width=\'306\' height=\'280\'></a>");
document.writeln("						  </div>");
document.writeln("						  <div class=\'swiper-slide\'>");
document.writeln("						  	<a href=\'http://www.hqyj.com/zhuanti/2019byj.html\' target=\'_blank\'><img src=\'http://www.hqyj.com/Ver201811/jiuye/images/article_main_022.jpg\' width=\'306\' height=\'280\'></a>");
document.writeln("						  </div>");
document.writeln("						</div>");
document.writeln("						<!-- Add Pagination -->");
document.writeln("						<div class=\'swiper-pagination\'></div>");
document.writeln("					  </div>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("					<div class=\'article_main_right_increase\'>");
document.writeln("						<div class=\'amri_title\'>");
document.writeln("							<em></em>");
document.writeln("							<p>华清图书馆</p>");
document.writeln("							<span>0元电子书，限时免费申领</span>");
document.writeln("						</div>");
document.writeln("						<div class=\'amri_main\'>");
document.writeln("							<p>10本华清图书<span>PDF版</span></p>");
document.writeln("							<em>扫码关注华清远见公众号<br><span style=\'color:#ff6960\'>自动回复“2”，</span>即可申领！</em>");
document.writeln("							<img src=\'http://www.hqyj.com/Ver201811/jiuye/images/erweim.jpg\'>");
document.writeln("						</div>");
document.writeln("					</div>");